import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "bjalogistic.id",
        pathname: "/wp-content/**",
      },
      {
        protocol: "https",
        hostname: "wgvzgvpqqoluavrwnufi.supabase.co",
        pathname: "/storage/**",
      },
      {
        protocol: "https",
        hostname: "invoice.bjalogistic.id",
        pathname: "/uploads/**",
      },
      {
        protocol: "https",
        hostname: "assets.bjalogistic.id",
      },
    ],
  },

  async redirects() {
    return [
      // ─── SERVICE PAGES (URL lama → URL baru) ───
      { source: "/cek-ongkir-cargo-darat", destination: "/layanan/cargo-darat", permanent: true },
      { source: "/ekspedisi-cargo-laut-dengan-kapal-cepat-roro-pelni", destination: "/layanan/cargo-laut", permanent: true },
      { source: "/cargo-udara", destination: "/layanan/cargo-udara", permanent: true },
      { source: "/kirim-motor", destination: "/layanan/kirim-motor", permanent: true },
      { source: "/kirim-mobil", destination: "/layanan/kirim-mobil", permanent: true },

      // ─── /jakarta-Asmat/Agats — dua segmen path, tidak bisa dijadikan halaman ───
      { source: "/jakarta-Asmat/Agats", destination: "/cargo/papua", permanent: true },

      // ─── /ekspedisi-jakarta-* di root (berbeda dari /cek-ongkir-cargo/) ───
      { source: "/ekspedisi-jakarta-Makassar", destination: "/kirim-ke/makassar", permanent: true },
      { source: "/ekspedisi-jakarta-Bone", destination: "/kirim-ke/bone", permanent: true },
      // ─── Redirect halaman kota lama (/blog/) → halaman /kirim-ke/ yang baru ───
      { source: "/blog/ekspedisi-jakarta-manokwari", destination: "/kirim-ke/manokwari", permanent: true },
      { source: "/blog/ekspedisi-jakarta-ambon", destination: "/kirim-ke/ambon", permanent: true },
      { source: "/blog/ekspedisi-jakarta-jayapura", destination: "/kirim-ke/jayapura", permanent: true },
      { source: "/blog/ekspedisi-jakarta-merauke", destination: "/kirim-ke/merauke", permanent: true },
      { source: "/blog/ekspedisi-jakarta-sorong", destination: "/kirim-ke/sorong", permanent: true },
      { source: "/blog/ekspedisi-jakarta-kupang", destination: "/kirim-ke/kupang", permanent: true },
      { source: "/blog/ekspedisi-jakarta-ternate", destination: "/kirim-ke/ternate", permanent: true },
      { source: "/blog/ekspedisi-jakarta-makassar", destination: "/kirim-ke/makassar", permanent: true },
      { source: "/blog/ekspedisi-jakarta-manado", destination: "/kirim-ke/manado", permanent: true },
      { source: "/blog/ekspedisi-jakarta-palu", destination: "/kirim-ke/palu", permanent: true },
      { source: "/blog/ekspedisi-jakarta-kendari", destination: "/kirim-ke/kendari", permanent: true },
      { source: "/blog/ekspedisi-jakarta-baubau", destination: "/kirim-ke/baubau", permanent: true },
      { source: "/blog/ekspedisi-jakarta-bone", destination: "/kirim-ke/bone", permanent: true },
      { source: "/blog/ekspedisi-jakarta-maros", destination: "/kirim-ke/maros", permanent: true },
      { source: "/blog/jakarta-fakfak", destination: "/kirim-ke/fakfak", permanent: true },
      { source: "/blog/jakarta-saumlaki", destination: "/kirim-ke/saumlaki", permanent: true },

      // ─── /bja/jasa-ekspedisi/* ───
      { source: "/bja/jasa-ekspedisi/jasa-cargo-darat", destination: "/layanan/cargo-darat", permanent: true },
      { source: "/bja/jasa-ekspedisi/jasa-cargo-laut", destination: "/layanan/cargo-laut", permanent: true },
      { source: "/bja/jasa-ekspedisi/jasa-cargo-udara", destination: "/layanan/cargo-udara", permanent: true },
      { source: "/bja/jasa-ekspedisi/jasa-pengiriman-alat-berat", destination: "/layanan/cargo-laut", permanent: true },
      { source: "/bja/jasa-ekspedisi/jasa-pengiriman-container", destination: "/layanan/cargo-laut", permanent: true },
      { source: "/bja/jasa-ekspedisi/project-logistics", destination: "/corporate", permanent: true },
      { source: "/bja/:path*", destination: "/", permanent: true },

      // ─── ARTIKEL RUTE KOTA LAMA (404 Coverage report 1 Sep 2026) → /kirim-ke/{kota} ───
      // 98 URL: /jakarta-{kota}, /ekspedisi-jakarta-{kota}, /cek-ongkir-cargo/ekspedisi-jakarta-{kota}
  { source: "/cek-ongkir-cargo/ekspedisi-jakarta-jayapura", destination: "/kirim-ke/jayapura", permanent: true },
  { source: "/cek-ongkir-cargo/ekspedisi-jakarta-larantuka", destination: "/kirim-ke/larantuka", permanent: true },
  { source: "/cek-ongkir-cargo/ekspedisi-jakarta-namlea", destination: "/kirim-ke/namlea", permanent: true },
  { source: "/cek-ongkir-cargo/ekspedisi-jakarta-tanimbar", destination: "/kirim-ke/tanimbar", permanent: true },
  { source: "/ekspedisi-jakarta-jayapura", destination: "/kirim-ke/jayapura", permanent: true },
  { source: "/ekspedisi-jakarta-manokwari", destination: "/kirim-ke/manokwari", permanent: true },
  { source: "/ekspedisi-jakarta-merauke", destination: "/kirim-ke/merauke", permanent: true },
  { source: "/ekspedisi-jakarta-sorong", destination: "/kirim-ke/sorong", permanent: true },
  { source: "/ekspedisi-jakarta-ternate", destination: "/kirim-ke/ternate", permanent: true },
  { source: "/jakarta-adonara", destination: "/kirim-ke/adonara", permanent: true },
  { source: "/jakarta-ambon", destination: "/kirim-ke/ambon", permanent: true },
  { source: "/jakarta-atambua", destination: "/kirim-ke/atambua", permanent: true },
  { source: "/jakarta-bacan", destination: "/kirim-ke/bacan", permanent: true },
  { source: "/jakarta-bajawa", destination: "/kirim-ke/bajawa", permanent: true },
  { source: "/jakarta-bantaeng", destination: "/kirim-ke/bantaeng", permanent: true },
  { source: "/jakarta-biak-numfor", destination: "/kirim-ke/biak-numfor", permanent: true },
  { source: "/jakarta-bintuni", destination: "/kirim-ke/bintuni", permanent: true },
  { source: "/jakarta-bitung", destination: "/kirim-ke/bitung", permanent: true },
  { source: "/jakarta-borong", destination: "/kirim-ke/borong", permanent: true },
  { source: "/jakarta-boven-digoel", destination: "/kirim-ke/boven-digoel", permanent: true },
  { source: "/jakarta-bulukumba", destination: "/kirim-ke/bulukumba", permanent: true },
  { source: "/jakarta-buol", destination: "/kirim-ke/buol", permanent: true },
  { source: "/jakarta-dabo", destination: "/kirim-ke/dabo", permanent: true },
  { source: "/jakarta-deiyai", destination: "/kirim-ke/deiyai", permanent: true },
  { source: "/jakarta-ende", destination: "/kirim-ke/ende", permanent: true },
  { source: "/jakarta-enrekang", destination: "/kirim-ke/enrekang", permanent: true },
  { source: "/jakarta-fakfak", destination: "/kirim-ke/fakfak", permanent: true },
  { source: "/jakarta-gorontalo", destination: "/kirim-ke/gorontalo", permanent: true },
  { source: "/jakarta-jailolo", destination: "/kirim-ke/jailolo", permanent: true },
  { source: "/jakarta-jayapura", destination: "/kirim-ke/jayapura", permanent: true },
  { source: "/jakarta-jayawijaya", destination: "/kirim-ke/jayawijaya", permanent: true },
  { source: "/jakarta-jeneponto", destination: "/kirim-ke/jeneponto", permanent: true },
  { source: "/jakarta-kaimana", destination: "/kirim-ke/kaimana", permanent: true },
  { source: "/jakarta-keerom", destination: "/kirim-ke/keerom", permanent: true },
  { source: "/jakarta-kefamenanu", destination: "/kirim-ke/kefamenanu", permanent: true },
  { source: "/jakarta-kolaka", destination: "/kirim-ke/kolaka", permanent: true },
  { source: "/jakarta-konawe-selatan", destination: "/kirim-ke/konawe-selatan", permanent: true },
  { source: "/jakarta-labuan-bajo", destination: "/kirim-ke/labuan-bajo", permanent: true },
  { source: "/jakarta-lanny-jaya", destination: "/kirim-ke/lanny-jaya", permanent: true },
  { source: "/jakarta-larantuka", destination: "/kirim-ke/larantuka", permanent: true },
  { source: "/jakarta-lembata", destination: "/kirim-ke/lembata", permanent: true },
  { source: "/jakarta-luwu-belopa", destination: "/kirim-ke/luwu-belopa", permanent: true },
  { source: "/jakarta-luwu-timur", destination: "/kirim-ke/luwu-timur", permanent: true },
  { source: "/jakarta-luwuk-banggai", destination: "/kirim-ke/luwuk-banggai", permanent: true },
  { source: "/jakarta-mamasa", destination: "/kirim-ke/mamasa", permanent: true },
  { source: "/jakarta-mamberamo-raya", destination: "/kirim-ke/mamberamo-raya", permanent: true },
  { source: "/jakarta-mamuju", destination: "/kirim-ke/mamuju", permanent: true },
  { source: "/jakarta-mappi", destination: "/kirim-ke/mappi", permanent: true },
  { source: "/jakarta-maros", destination: "/kirim-ke/maros", permanent: true },
  { source: "/jakarta-masohi", destination: "/kirim-ke/masohi", permanent: true },
  { source: "/jakarta-maumere", destination: "/kirim-ke/maumere", permanent: true },
  { source: "/jakarta-membarmo-raya", destination: "/kirim-ke/mamberamo-raya", permanent: true },
  { source: "/jakarta-merauke", destination: "/kirim-ke/merauke", permanent: true },
  { source: "/jakarta-mimika", destination: "/kirim-ke/mimika", permanent: true },
  { source: "/jakarta-morowali", destination: "/kirim-ke/morowali", permanent: true },
  { source: "/jakarta-nabire", destination: "/kirim-ke/nabire", permanent: true },
  { source: "/jakarta-nagekeo", destination: "/kirim-ke/nagekeo", permanent: true },
  { source: "/jakarta-namlea", destination: "/kirim-ke/namlea", permanent: true },
  { source: "/jakarta-palopo", destination: "/kirim-ke/palopo", permanent: true },
  { source: "/jakarta-palu", destination: "/kirim-ke/palu", permanent: true },
  { source: "/jakarta-pangkep", destination: "/kirim-ke/pangkep", permanent: true },
  { source: "/jakarta-paniai", destination: "/kirim-ke/paniai", permanent: true },
  { source: "/jakarta-parigi-mountong", destination: "/kirim-ke/parigi-mountong", permanent: true },
  { source: "/jakarta-pasang-kayu", destination: "/kirim-ke/pasang-kayu", permanent: true },
  { source: "/jakarta-pinrang", destination: "/kirim-ke/pinrang", permanent: true },
  { source: "/jakarta-puncak-jaya", destination: "/kirim-ke/puncak-jaya", permanent: true },
  { source: "/jakarta-raja-ampat", destination: "/kirim-ke/raja-ampat", permanent: true },
  { source: "/jakarta-rantepao", destination: "/kirim-ke/rantepao", permanent: true },
  { source: "/jakarta-rappang", destination: "/kirim-ke/rappang", permanent: true },
  { source: "/jakarta-rote-ndao", destination: "/kirim-ke/rote-ndao", permanent: true },
  { source: "/jakarta-ruteng", destination: "/kirim-ke/ruteng", permanent: true },
  { source: "/jakarta-sarmi", destination: "/kirim-ke/sarmi", permanent: true },
  { source: "/jakarta-sentani", destination: "/kirim-ke/sentani", permanent: true },
  { source: "/jakarta-seram", destination: "/kirim-ke/seram", permanent: true },
  { source: "/jakarta-serui", destination: "/kirim-ke/serui", permanent: true },
  { source: "/jakarta-sidrap", destination: "/kirim-ke/sidrap", permanent: true },
  { source: "/jakarta-soe", destination: "/kirim-ke/soe", permanent: true },
  { source: "/jakarta-soppeng", destination: "/kirim-ke/soppeng", permanent: true },
  { source: "/jakarta-sorowako", destination: "/kirim-ke/sorowako", permanent: true },
  { source: "/jakarta-sumba-barat-daya", destination: "/kirim-ke/sumba-barat-daya", permanent: true },
  { source: "/jakarta-sumba-timur", destination: "/kirim-ke/sumba-timur", permanent: true },
  { source: "/jakarta-supiori", destination: "/kirim-ke/supiori", permanent: true },
  { source: "/jakarta-takalar", destination: "/kirim-ke/takalar", permanent: true },
  { source: "/jakarta-tanimbar", destination: "/kirim-ke/tanimbar", permanent: true },
  { source: "/jakarta-tapoyo", destination: "/kirim-ke/topoyo", permanent: true },
  { source: "/jakarta-tiakur", destination: "/kirim-ke/tiakur", permanent: true },
  { source: "/jakarta-tidore", destination: "/kirim-ke/tidore", permanent: true },
  { source: "/jakarta-tobelo", destination: "/kirim-ke/tobelo", permanent: true },
  { source: "/jakarta-tojo-una-una", destination: "/kirim-ke/tojo-una-una", permanent: true },
  { source: "/jakarta-toli-toli", destination: "/kirim-ke/toli-toli", permanent: true },
  { source: "/jakarta-tolikara", destination: "/kirim-ke/tolikara", permanent: true },
  { source: "/jakarta-tual", destination: "/kirim-ke/tual", permanent: true },
  { source: "/jakarta-wajo", destination: "/kirim-ke/wajo", permanent: true },
  { source: "/jakarta-wamena", destination: "/kirim-ke/wamena", permanent: true },
  { source: "/jakarta-waropen", destination: "/kirim-ke/waropen", permanent: true },
  { source: "/jakarta-weda", destination: "/kirim-ke/weda", permanent: true },
  { source: "/jakarta-yahukimo", destination: "/kirim-ke/yahukimo", permanent: true },
  { source: "/jakarta-yapen", destination: "/kirim-ke/yapen", permanent: true },

      // ─── JADWAL KAPAL LAMA (per-bulan, selalu expired) → hub /jadwal-kapal ───
      { source: "/jadwal-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-kapal-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/rute-jadwal-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/rute-dan-jadwal-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/rute-dan-jadwal-kapal-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-dan-rute-terbaru-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-lengkap-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-rute-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-rute-terbaru-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/jadwal-rute-kapal-pelni-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/informasi-lengkap-rute-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/update-jadwal-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/update-jadwal-rute-km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/kapal-cargo-jadwal-kapal-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/km-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/blog/jadwal-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/blog/rute-:slug", destination: "/jadwal-kapal", permanent: true },
      { source: "/category/jadwal-kapal", destination: "/jadwal-kapal", permanent: true },

      // ─── PANDUAN CEK ONGKIR/RESI LAMA → halaman fungsi terkait ───
      { source: "/cara-cek-ongkir-:slug", destination: "/cek-ongkir", permanent: true },
      { source: "/:num(\\d+)-cara-cek-ongkir-:slug", destination: "/cek-ongkir", permanent: true },
      { source: "/cara-cek-resi-:slug", destination: "/tracking", permanent: true },
      { source: "/cek-resi-:slug", destination: "/tracking", permanent: true },
      { source: "/:num(\\d+)-cara-cek-resi-:slug", destination: "/tracking", permanent: true },
      { source: "/cara-lacak-paket-:slug", destination: "/tracking", permanent: true },
      { source: "/cara-tracking-:slug", destination: "/tracking", permanent: true },

      // ─── HALAMAN STATIS LAMA → halaman baru ───
      { source: "/tentang-kami", destination: "/kontak", permanent: true },
      { source: "/privacy-policy", destination: "/privacy", permanent: true },
      { source: "/terms-conditions", destination: "/terms", permanent: true },
      { source: "/layanan", destination: "/layanan/cargo-laut", permanent: true },
      { source: "/gallery", destination: "/", permanent: true },
      { source: "/news", destination: "/blog", permanent: true },
    ];
  },
};

export default nextConfig;
