import Link from "next/link";
import type { Metadata } from "next";
import { ChevronRight, MapPin, ArrowRight } from "lucide-react";
import { regionConfigs } from "@/lib/data/regions";
import { BreadcrumbJsonLd } from "@/components/JsonLd";

const BASE_URL = "https://bjalogistic.id";

export const metadata: Metadata = {
  title: "Cargo ke Papua, Maluku, NTT & Sulawesi",
    description:
        "Jasa ekspedisi cargo ke seluruh Indonesia Timur: Papua, Maluku, NTT, dan Sulawesi. Cek harga, estimasi transit, dan jadwal kapal per wilayah.",
          alternates: { canonical: `${BASE_URL}/cargo` },
            openGraph: {
                title: "Cargo ke Papua, Maluku, NTT & Sulawesi | BJA Logistic",
                    description:
                          "Jasa ekspedisi cargo ke seluruh Indonesia Timur. Cek harga dan jadwal kapal per wilayah tujuan.",
                              url: `${BASE_URL}/cargo`,
                                  images: [{ url: "/og-image.png", width: 1200, height: 630 }],
                                    },
                                    };

                                    export default function CargoHubPage() {
                                      return (
                                          <>
                                                <BreadcrumbJsonLd
                                                        items={[
                                                                  { name: "Beranda", url: BASE_URL },
                                                                            { name: "Cargo", url: `${BASE_URL}/cargo` },
                                                                                    ]}
                                                                                          />

                                                                                                <div className="min-h-screen bg-[#F8FAFC]">
                                                                                                        <div className="relative bg-gradient-to-br from-[#CC1F2A] to-[#8B1219] w-full">
                                                                                                                  <div className="relative max-w-6xl mx-auto px-4 py-10 sm:py-12 w-full min-w-0">
                                                                                                                              <nav aria-label="Breadcrumb" className="flex items-center gap-1.5 text-white/70 text-xs sm:text-sm mb-6">
                                                                                                                                            <Link href="/" className="hover:text-white transition-colors">Beranda</Link>
                                                                                                                                                          <ChevronRight size={13} />
                                                                                                                                                                        <span className="text-white font-semibold">Cargo</span>
                                                                                                                                                                                    </nav>
                                                                                                                                                                                    
                                                                                                                                                                                                <h1 className="text-2xl sm:text-3xl lg:text-4xl font-black text-white leading-tight mb-4 max-w-xl">
                                                                                                                                                                                                              Cargo ke Seluruh Indonesia Timur
                                                                                                                                                                                                                          </h1>
                                                                                                                                                                                                                                      <p className="text-white/70 text-sm sm:text-base max-w-lg leading-relaxed">
                                                                                                                                                                                                                                                    Pilih wilayah tujuan untuk lihat harga, estimasi waktu transit, dan jadwal kapal terbaru.
                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                          <div className="max-w-6xl mx-auto px-4 py-10">
                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                                                                                                                                                                                                                                                                                                                {regionConfigs.map((r) => (
                                                                                                                                                                                                                                                                                                                              <Link
                                                                                                                                                                                                                                                                                                                                              key={r.slug}
                                                                                                                                                                                                                                                                                                                                                              href={`/cargo/${r.slug}`}
                                                                                                                                                                                                                                                                                                                                                                              className="group bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-lg hover:border-[#CC1F2A]/30 transition-all p-6 flex flex-col"
                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 mb-3">
                                                                                                                                                                                                                                                                                                                                                                                                                              <MapPin size={18} className="text-[#CC1F2A]" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                <h2 className="text-lg font-black text-[#111111]">{r.label}</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-500 mb-4 flex-1">{r.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex gap-2 flex-wrap mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {r.stats.map((s) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key={s.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="inline-flex items-center gap-1 bg-gray-50 border border-gray-200 text-gray-600 text-xs font-semibold px-2.5 py-1 rounded-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <strong className="text-[#CC1F2A]">{s.value}</strong> {s.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="inline-flex items-center gap-1.5 text-sm font-bold text-[#CC1F2A] group-hover:gap-2.5 transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Lihat harga & jadwal
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <ArrowRight size={15} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
